### PR TITLE
Add functionality to the backtesting market and indicator graphs

### PR DESCRIPTION
**Pull request by thetestspecimen**
Indicators can now be added to both the market graph and three
independent indicator graphs below the market. The user can opt to
have the indicators assigned automatically or have full control over
where they are placed by using specific syntax when initialising the
indicators in the strategy file for gekko.

The relevant adjustments are detailed below

- always display candlesticks for the market to avoid confusion with
  market indicators
- add three permanent indicator graphs below the market graph
- set market and three indicator graphs to fill screen vertically on a
  1080p monitor
- set six groups with different ranges to cover all possible indicator
  ranges
- change market up to green and market down to red, as they were
  inverted in the candlestick chart
- add missing talib indicators to the indicators array
- make pattern indicators display on the market as a diamond marker
  with the name of the pattern above the diamond
- change location of buy and sell indicators on the market to be
  further away from the candles to stop interference
- add ability to specify which graph an indicator is displayed on
- add ability to auto-assign an indicator based on its absolute values
- update readme to give instructions on use of new features
- add new screenshots to readme and assets folder

### CODE REVIEW

**Comment by H256** [comment]
Hi @thetestspecimen - thanks for this wonderful contribution! I will test and review during the next week and then merge. ;)

**Comment by H256** [comment]
@thetestspecimen I have tested and found, that it doesn't work with most of the gekko native strategies (or any strategy that uses less than 3 indicators). Would you mind having a look at this again?

To reproduce - select _RSI_ or _MACD_ native strategy for example (both have only one indicator result per candle). It will not render the chart, giving the error 
```
[Vue warn]: Error in mounted hook: "TypeError: options.xAxis[2] is undefined"

found in

---> <VueEchartWrapper> at src/components/global/chart.vue
       <QCardSection>
         <QCard>
           <Result> at src/components/backtester/result/result.vue
             <Backtester> at src/components/backtester/backtester.vue
               <QPage>
                 <BacktesterPage> at src/pages/backtest.vue
                   <QPageContainer>
                     <QLayout>
                       <MainLayoutPage> at src/layouts/default.vue
                         <App> at src/App.vue
                           <Root>
```
This is true for all other strategies using < 3 Indicators. 
All other things here look good to me.

**Comment by thetestspecimen** [comment]
Ok. No problem. I will take a look at this and get back to you.

I tend to use talib indicators rather than the gekko indicators. Although I did run through a few gekko indicators as a test and didn't hit a problem. We will see...

**Comment by H256** [comment]
Reviewed. Looks very good.

**Pull request merged**
